using Microsoft.VisualStudio.TestTools.UnitTesting;
using Conductor_Server.Server;
using System;
using System.Collections.Generic;
namespace Conductor_Server.Tests.Server
{
    [TestClass]
    public class UnitTest1
    {
        [TestMethod]
        public void TestMethod1()
        {
            //create engine
            //Conductor_Server.Core core = new Conductor_Server.Core();
            //core.Initialize();

            ////create hub. events are static, so core should pick them up
            //CommHub hub = new CommHub();
            //hub.SendErrorMessage("this is a error message generated by mstest",
            //    new List<string>()
            //    {
            //        "errormessage1",
            //        "errormessage2",
            //        "errormessage3"
            //    },
            //    new Conductor_Shared.WorkPackage()
            //    {
            //        GUID = Guid.Parse("11111111-1111-1111-1111-111111111111"),
            //        Version = new Conductor_Shared.Version()
            //        {
            //            Major = 0,
            //            Minor = 111,
            //        }
            //    });

            //test should write an output error message to %APPDATA%/assets/v0.111/errorlogs/11111111-1111-1111-1111-111111111111-0.log
        }
    }
}
