version: '3'
services:
  app:
    image: chemsorly/conductor:latest-server-master
    restart: always
    stdin_open: true #workaround to keep app alive
    volumes:
        - C:/DockerHost/Conductor/master:C:/app/workdir #in case you want to directly access the files
    environment: 
        - CONDUCTOR_HOST=https://example.org
    ports:
        - 8080:8080
networks:
  default:
    external:
      name: nat
